# Generated by Django 3.0.6 on 2020-05-19 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=256)),
                ('line2', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('pincode', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Address',
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('amount', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Fee Payment',
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('branch', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=256)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('branch', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=15)),
                ('father_name', models.CharField(max_length=256)),
                ('father_phone', models.CharField(max_length=256)),
                ('father_email', models.EmailField(max_length=254)),
                ('mother_name', models.CharField(max_length=256)),
                ('mother_phone', models.CharField(max_length=256)),
                ('mother_email', models.EmailField(max_length=254)),
                ('annual_income', models.CharField(max_length=20)),
                ('has_institute_access', models.BooleanField(default=False)),
                ('image', models.CharField(default='/static/img/default-user-image.png', max_length=256)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=5)),
                ('day', models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1)),
                ('duration', models.CharField(default='60', max_length=5)),
                ('course', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Time Table',
            },
        ),
        migrations.CreateModel(
            name='Student_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Address')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
            ],
            options={
                'verbose_name_plural': 'Student Address',
            },
        ),
        migrations.CreateModel(
            name='FeePaymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'Paid'), ('u', 'Unpaid')], max_length=1)),
                ('fees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.FeePayment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
            ],
            options={
                'verbose_name_plural': 'Fee Payment Status',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
                ('time_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TimeTable')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=256)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
            ],
        ),
    ]
